### ISSUE TITLE
Expliquer l'usage des formats propriétaires

### ISSUE THREAD

**Issue by MattiSG** [sgmap/pix#157]
En tant que militant du logiciel libre,
Je peux comprendre pourquoi les tests proposent des documents au format Office,
Pour ne pas croire que PIX est une conséquence de l'accord entre l'Éducation nationale et Microsoft.

**Comment by openelearning** [comment]
+1

**Comment by jbuget** [comment]
Depuis quelques semaines, Pix propose de télécharger plusieurs formats de fichiers pour les épreuves concernées. Nous n'avons plus eu de retours ayant trait à ce sujet depuis lors. Je me permets donc de clore cette issue. Si la feature et ma réponses vous semblent incomplets ou à côté de la plaque, sentez-vous libre de réouvrir l'issue (en expliquant ce qui manque / peut  être amélioré) :-)
