### ISSUE TITLE
Stabiliser les devDependencies et dependencies du package.json de l'API

### ISSUE THREAD

**Issue by bdavidxyz** [sgmap/pix#159]
Sinon on ne sait pas quelle version est déployée, étant donné que sur nos postes de développements nous ne passons pas notre temps à supprimer le node_modules et tout réinstaller (mais la CI prends ce temps là, donc...)

**Comment by jbuget** [comment]
il est prévu de passer à Yarn dès qu'on aura effectué la migration vers Ember 2.12 (LTS), qui elle-même supporte Yarn.
