### ISSUE TITLE
Accessibility of forms

### ISSUE THREAD

**Issue by nico3333fr** [sgmap/pix#186]
Hi there,

there are a some accessibility issues : 

FORMS :
- Add label for="" to field descriptions for tests answers
- Same for home page for newsletter description

Hx:
- on the home page, there are only h4, no h1 and a proper Hx structure
- no heading on tests

Etc.
Kind regards,
Nicolas

**Comment by ryuran** [comment]
More informations about this issue:

French government website have to respect RGAA. http://references.modernisation.gouv.fr/rgaa-accessibilite

Form and label:
http://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#crit-11-1

Structure:
http://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#structure

**Comment by jbuget** [comment]
The accessibility of the platform will be soon one our main focus for the coming weeks. Thank you for your feedback. :-)

**Comment by Akhilian** [comment]
We changed our HTML structure recently that should solve some of theses problems.
See #288  

Many a11y tasks are already planned.
