### ISSUE TITLE
La page des tests adaptatifs n'est rafraîchie que quand on fait « Précédent »

### ISSUE THREAD

**Issue by jilljenn** [sgmap/pix#188]
http://staging.pix.beta.gouv.fr/placement-tests
Mais maintenant le chat apparaît bien. C'est étrange.

**Comment by Akhilian** [comment]
@jilljenn Salut ! Est-ce que cette issue est toujours d'actu ?
Si oui, peux-tu décrire un peu plus le bug et comment le reproduire ?

Merci ! :D
