### ISSUE TITLE
Comment collaborer sur les questions proposées sur pix.beta.gouv.fr ?

### ISSUE THREAD

**Issue by openelearning** [sgmap/pix#190]
Bonjour,
Au sein du mailing liste dédiée à l'éducation, nous avons pu découvrir et échanger sur pix.
Est-il possible de créer de nouvelles questions et proposer des améliorations pour des questions existantes ?
Si oui, comment pouvons nous le faire ?
Je transmettrai ensuite votre réponse à cette mailing liste.
(Nous avons aussi demandé sur contact@pix.beta.gouv.fr mais n'avons pas encore eu de retours).
Merci

**Comment by jbuget** [comment]
Bonjour @openelearning,

Désolé de répondre aussi tardivement, nous avons énormément de demandes à traiter depuis la sortie de la plateforme il y a presque 6 mois.

Nous avons, depuis le temps, mis en production la fonctionnalité de "signalement d'une épreuve" qui permet de donner son avis / exprimer son désaccord pour une épreuve en particulier depuis la page des résultat d'une évaluation.

Dans les jours qui viennent, nous nous apprêtons à livrer la fonctionnalité de signalement d'une épreuve directement depuis l'épreuve en question.

Pour ce qui est de proposer des nouvelles questions, je vous invite à adresser vos suggestions à contact@pix.beta.gouv.fr.

Jérémy.
