### ISSUE TITLE
Pourquoi les épreuves d'un test sont données dans l'ordre chronologique inverse ?

### ISSUE THREAD

**Issue by jilljenn** [sgmap/pix#201]
Dans `course-serializer.js`, curieusement il y a `unshift` au lieu de `push`.
Cf. aussi `course-serializer_test.js` pour comprendre encore moins. Pourquoi ce choix ?

**Comment by bdavidxyz** [comment]
+1. Si ce n'est pas un bug il faudrait un commentaire dans le code pour expliquer pourquoi

**Comment by jilljenn** [comment]
OK c'est bien parce que Airtable fait n'importe quoi et renvoie les challenges dans l'autre ordre. On ajoute un commentaire.

**Comment by bdavidxyz** [comment]
C'est le mode de fonctionnement internet de Airtable, on ne peut pas le changer. https://github.com/Airtable/airtable.js/issues/17
