### ISSUE TITLE
Impossible de tester le temps dans le composant Timeout-jauge

### ISSUE THREAD

**Issue by yojecode** [sgmap/pix#225]
Les cas sont les suivants :
- Le timer se décharge progressivement
- Quand le décompte est terminé, le timer reste à 0:00
- Quand le timer est à 0:00, le picto s'affiche en rouge
- L'arrêt du timer ne change pas l'url

**Comment by bdavidxyz** [comment]
C'est corrigé.

Ensemble des tests à faire : 

timer défini, on l'affiche
n'existe pas, on le masque
afficher jauge selon valeur backend
timer décharge progressivement
timer s'affiche en min/sec
timer reste à 0:00 qd fini
picto rouge si fini
6 cas de figure : l'utilisateur a passé  / validé, a combiner avec tps > 0, tps = 0, tps < 0
capacité d'afficher tps dépassé ds ecran resultats
back : bonne rép + temps dépassé = temps dépassé
back : mauv rép + temps dépassé = mauvaise rép
back : aband + tps dépassé = aband

**Comment by bdavidxyz** [comment]
Notez qu'on "skippe" le temps lui-même
