### ISSUE TITLE
La liste des tests adaptatifs n'est pas rafraîchie lorsqu'on fait POST /api/courses

### ISSUE THREAD

**Issue by jilljenn** [sgmap/pix#243]
J'avais 3 tests sur http://317-adaptive-scenarios.pix.beta.gouv.fr/placement-tests

J'ai mis à jour Airtable en conséquence, en retirant les flags isAdaptive.
Je suis censé avoir mis à jour le cache en faisant des requêtes POST aux /api/courses/ID correspondants.

Pourtant, j'ai toujours 3 tests sur http://317-adaptive-scenarios.pix.beta.gouv.fr/placement-tests alors que même si je fais GET /api/courses/ID, je n'ai plus le flag isAdaptive.

Bravo Ember Data.

**Comment by Akhilian** [comment]
@jilljenn une requête PUT sur /api/courses devrait faire le taf ;)
