### ISSUE TITLE
Les solutions ne chargent pas à la fin d'un test adaptatif

### ISSUE THREAD

**Issue by jilljenn** [sgmap/pix#287]
À cause de cette ligne :
https://github.com/sgmap/pix/blob/dev/api/lib/application/assessments/assessment-controller.js#L70

Qui en gros, force l'apprenant à répondre à toutes les questions du test avant de lui révéler les réponses. Mais c'est justement ce qu'il ne fait pas dans un test adaptatif :)

## Solution rapide

Ajouter une condition, si le test est adaptatif, qui vérifie, via la table `scenarios`, si le test est effectivement terminé.

## Solution propre

Ajouter un flag `status` aux assessments. Qu'en pensez-vous ? Je peux coder la version rapide pour l'instant.

**Comment by bdavidxyz** [comment]
Oui il ya même un test auto pour être sur qu'on attend bien la fin du test :) 

Qu'entends-tu par flag status ? il servirait à quoi ?

**Comment by jilljenn** [comment]
Désolé :) Je ne suis jamais clair dans mes issues.

Un test adaptatif pose moins de questions de la banque qu'un test normal (genre 1.1 pose 20 questions max alors qu'il n'y en a 41 dans la base).

Donc on pourrait mettre un flag status dans assessment qui indique "ongoing" ou "finished".

En attendant je peux changer la condition.

**Comment by Akhilian** [comment]
@jilljenn Salut ! Est-ce que cette issue est toujours d'actu ?
Si oui, peux-tu décrire un peu plus le bug et comment le reproduire ?

Merci ! :D
