### ISSUE TITLE
les fonts en gras le sont trop

### ISSUE THREAD

**Issue by bdavidxyz** [sgmap/pix#325]
Par exemple, le "je valide" est trop gras. Il y a une tonne d'exemple comme celui-ci. Probablement lié à l'import de la font 900. Problème à traiter "proprement" avec variabilisation SASS des font-weight.

<img width="233" alt="screen shot 2017-03-06 at 13 50 03" src="https://cloud.githubusercontent.com/assets/2937888/23610720/e9c856e8-0273-11e7-84fa-6da439f3ef17.png">

**Comment by jbuget** [comment]
Résolu lors du redesign de la home
