### ISSUE TITLE
homgénéiser la façon d'écrire un component Ember

### ISSUE THREAD

**Issue by bdavidxyz** [sgmap/pix#336]
Nous avons eu le problème avec Florian lors d'une scéance de pair-prog.

=> On ouvre un composant Ember qui est plutôt gros et qu'on n'a pas écrit.
=> Et voilà, c'est très dur de deviner ce qui relève : 

 - de la propriété passée en paramètre
 - de la méthode privée
 - du hook de lifecycle Ember
 - des propriétés publiques utilisées pour l'affichage

et j'en oublie peut être.

  Je propose des conventions bien lourdes et bien grasses pour être sûr de s'y retrouver à tous les coups. Surtout que pour tous les composants il y aura TOUJOURS les mêmes artefacts.

  Par exemple
 - en Javascript une méthode dite privée commence par "_" (underscore) - même si on peut y accéder de l'extérieur, ça veut dire "attention j'ai désigné cette méthode en tant que méthode privée".

 - pour les Ember lifecycle hook, on peut mettre le commentaire // Ember lifecycle hook, juste au-dessus de chaque fonction. On peut faire autrement bien sûr, c'est à discuter.

Mais ne rien faire rend la lecture d'un component inutilement compliquée.

**Comment by jbuget** [comment]
A défaut de refaire une passe sur tous nos composants, est-ce que la section de Wiki suivante suffit pour clore l'issue ?

https://github.com/sgmap/pix/wiki/Standards-ember.js#structure-dun-composant

**Comment by yojecode** [comment]
@jbuget @brm on peut fermer cette issue
