### ISSUE TITLE
labeled-checkbox, *-as-object ... Utils, Mixins ou autres ?

### ISSUE THREAD

**Issue by MBrandone** [sgmap/pix#359]
Prendre une decision sur comment gère t-on les fonctions utilitaires, et garder un code dry.
(Parsing des labels d'inputs, avec ou sans placeholder, transformation des strings answers en objets, tableau ...)

**Comment by jbuget** [comment]
02/05/2017 : nosu avons tenté de faire le point. On a décidé de ne pas décidé et d'attendre qu'un autre cas se reproduise pour discuter ensemble.

Ce qu'on a vu en séance : 
- il existe un générateur pour les mixins : `ember g mixin mixin-name`
- il existe un générateur pour les utils : `ember g util util-name`
- les mixins ne sont pas documentés ([hors doc API](https://emberjs.com/api/classes/Ember.Mixin.html#content)) dans la doc Ember
- les utils sont documentés [sur une page, avec les services](https://guides.emberjs.com/v2.13.0/tutorial/service/#toc-toggle).
- les mixins permettent de [rajouter du comportement / de la data à un Ember.Object](http://stackoverflow.com/questions/35269346/whats-difference-between-mixins-and-services-on-emberjs)
- les utils sont de simples fonctions exportées

Ce qu'on se dit sans vraiment trancher : 
- on implémente plutôt une mixin dans le cas d'un Component
- on implémente plutôt un util dans le cas d'un service ou un truc unitaire

Ex : 
- si on veut mutualiser un champs "email avec validation" pour des formulaires, on aura tendance à faire une mixin
- si on veut simplement une méthode de validation d'un email – email-validator – on aura tendance à faire un util
- dans ce cas en particulier, il paraîtrait pertinent de faire une mixin mixin-email et qui contient la data `email` en plus de la logique de déclenchement de la validation, laquelle serait définie dans un util ;
- moralité : on peut utiliser un util dans une mixin ; l'inverse n'est pas vrai

**Comment by jbuget** [comment]
Une partie des mixins a été remplacée par de sutils dans la PR #419
