### ISSUE TITLE
Componentiser chaque entrée d'un qrocm-ind dans le panneau de correction (comparison-window>qrocm-ind-solution-panel)

### ISSUE THREAD

**Issue by MBrandone** [sgmap/pix#363]
La boucle la computed property inputFields dans qrocm-ind-solution-panel consisté à créer un tableau qui va structer les données à  afficher pour chaque champs de réponse (label, answer, solution, resultat).

Pour avoir un composant, qrocm-ind-solution-panel plus propre (supprimer les fonctions privées, ne pas avoir le forEach qui structure les données). On pourrait créer un composant field, dont le role est d'afficher pour chaque entrée du qrocm-ind, le label, la reponse donnée, la solution, dans le bon format (resultDetails).

Ce composant pourra être ensuite réutilisé dans qrocm-dep-solution-panel

**Comment by mackwic** [comment]
too old, closing
