### ISSUE TITLE
Refactorer le composant `challenge-item-generic.js`

### ISSUE THREAD

**Issue by jbuget** [sgmap/pix#377]
En l'état, le composant `challenge-item-generic.js` est un énorme plat de spaghetti imbitable. La complexité de ce composant vient des besoins fonctionnels associés : 
- gestion du timer
- affichage d'une fenêtre modale d'avertissement qu'il s'agit d'une épreuve chronométrée.

Parmi les choses à revoir : 
- la mutualisation de `_.isInteger(this.get('challenge.timer'))`
- d'ailleurs, pourquoi `_.isInteger` pour décider que l'épreuve est timée ?
- et d'ailleurs, pourquoi ne pas utiliser la méthode built-in `Number.isInteger` ?
- doit-on forcément passer par une variable de fichier (`warningConfirmationSent`) ?
- pourquoi lance-t-on le timer seulement quand il s'agit (apparemment) d'une épreuve non-timée (?!)
- etc.

**Comment by mackwic** [comment]
too old, closing
