### ISSUE TITLE
Refactorer la route POST /api/courses/ qui permet de vider le cache pour les courses et de les recharger.

### ISSUE THREAD

**Issue by Hypernikao** [sgmap/pix#452]
L'idée est de : 
- [ ] troquer le verbe POST pour un verbe DELETE
- [ ] déplacer la méthode CourseController#refresh directement dans le CacheController
- [ ] simplifier la méthode pour qu'elle se contente de supprimer la clé (algo plus simple) sans retourner les nouveaux courses à jour

**Comment by mackwic** [comment]
fixed
