### ISSUE TITLE
Le mot de passe « coucou 42 » ne passe pas la page d'inscription

### ISSUE THREAD

**Issue by jilljenn** [sgmap/pix#493]
Ça dit qu'il faut une lettre, un chiffre, etc.

**Comment by Akhilian** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BUG mot de passe "coucou 42"](https://trello.com/c/uWB0Ngil/663-bug-mot-de-passe-coucou-42)

**Comment by mackwic** [comment]
fixed
