### ISSUE TITLE
Annoying depreciation warning in the console in dev mode

### ISSUE THREAD

**Issue by bdavidxyz** [sgmap/pix#57]
<img width="1233" alt="screen shot 2016-09-22 at 11 42 46" src="https://cloud.githubusercontent.com/assets/2937888/18743541/c4b2be70-80b9-11e6-8042-d24c523b542a.png">

**Comment by jbuget** [comment]
Should be fixed with Ember upgrade (especially with session service refactoring) https://github.com/sgmap/pix-live/pull/65

**Comment by bdavidxyz** [comment]
Fini, depuis que la session a été supprimée. Seul un warning de progressbar s'affiche, une issue a été faite à part.
