### ISSUE TITLE
Le lien "Définir un nouveau mot de passe" ne semble pas marcher du premier coup

### ISSUE THREAD

**Issue by Flightan** [sgmap/pix#632]
J'ai cliqué sur le lien contenu dans le mail d'oubli de mot de passe dès sa réception et suis revenu sur la page d'accueil de PIX - `https://pix.beta.gouv.fr/`

J'ai réessayé 1 minute plus tard et suis bien arrivé sur `https://pix.beta.gouv.fr/changer-mot-de-passe/{{token}}`

**Comment by mackwic** [comment]
Fixé
