### ISSUE TITLE
Controllers are icky

### ISSUE THREAD

**Issue by bdavidxyz** [sgmap/pix#64]
Controllers must be slim.

Components communicate to Router through actions.

Thus, we will have a clean Separation Of Concerns, as well as a unique way of coding functionalities.

See https://emberigniter.com/should-we-use-controllers-ember-2.0/

**Comment by jbuget** [comment]
T'as pu tester si ça marche jusqu'au bout de se passer des controllers et de laisser faire les routes ?

**Comment by bdavidxyz** [comment]
Oui j'avais réussi

**Comment by jbuget** [comment]
Finalement, après relecture approfondie de la documentation d'Ember, discussions sur le Slack d'Ember et moultes expérimentations sur Ember au travers de pet projects, il apparaît que, s'il est préférable et recommandé d'utiliser les routes pour gérer le templating et le databinding (dont Computed Properties), l'usage des controllers pour gérer les transitions de routes et faire remonter les actions depuis un (sous-)composant jusqu'à la route reste d'actualité dans Ember.

L'argument qui m'a convaincu de revoir mon avis est que : l'une des convictions d'Ember est de garantir des évolutions techniques ou d'archi de façon sécurisée et pérenne.

En conséquence de quoi, je me permets de clore cette issue. Si vous n'êtes pas convaincu, merci de ré-ouvrir l'issue / le débat, en argumentant. :-)
