### ISSUE TITLE
Monter de version Ember 2.8 -> 2.9 sur PIX-Live

### ISSUE THREAD

**Issue by jbuget** [sgmap/pix#90]
- Release note : http://emberjs.com/blog/2016/10/17/ember-2-9-released.html
- Changelog : https://github.com/emberjs/data/blob/v2.9.0/CHANGELOG.md
- Upgrading : https://ember-cli.com/user-guide/#upgrading

**Comment by yojecode** [comment]
@jbuget Cette issue peut-être close n'est-ce pas ?

**Comment by bdavidxyz** [comment]
on est déjà à 2.11
